import constants from './constants';
import themes from './themes';

const {
    routes,
    footer,
    header,
    home,
    signin,
    signup,
    paymentMethods,
    productCard,
    product,
    cart,
    checkout,
    order,
    orderStatus,
    deliveryAddress,
    singleProduct,
    profile,
    profileSideBar,
    global,
} = require('~/data/config.json');

export {
    routes as route,
    footer,
    header,
    themes,
    constants,
    paymentMethods,
    home,
    signin,
    signup,
    productCard,
    product,
    cart,
    checkout,
    order,
    orderStatus,
    deliveryAddress,
    singleProduct,
    profile,
    profileSideBar,
    global,
};
